# Generated by Django 6.0 on 2026-03-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_download'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
